### ISSUE TITLE
Error: Cannot find module 'esm'

### ISSUE THREAD

**Issue by orchoban** [orchoban/react.cordova#2]
`Error: Cannot find module 'esm'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\or\AppData\Roaming\npm\node_modules\react.cordova\.bin\reco:3:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)`

**Comment by orchoban** [comment]
This error exists between versions reco(react.cordova)@1.5.6 to reco(react.cordova)@1.6.1 .
Has been fixed in version @1.6.1 and above
